import { FlexWrapper } from "../../../../StyledComponents/FlexWrapper/FlexWrapper";
import { Span } from "../../../../StyledComponents/Span/Span";

export const IndexNewProducts = () => {
  return (
    <>
      <FlexWrapper
        width="100%"
        flexDirection="column"
        alignItems="center"
        justifyContent="center"
        padding="50px"
        gap="40px"
      >
        <Span
          fontSize="36px"
          color="#ffffff"
          fontFamily="'PT Sans', sans-serif;"
        >
          НОВЫЕ ПОСТУПЛЕНИЯ
        </Span>
        <Span width="120px" borderBottom="1px solid #ffffff"></Span>
        <FlexWrapper padding="20px" alignItems="center" justifyContent="center" gap="30px" flexWrap="wrap">
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
          <FlexWrapper
            height="300px"
            width="250px"
            backgroundCcolor="#ffffff"
            alignItems="center"
            justifyContent="center"
          >
            ТОВАР
          </FlexWrapper>
        </FlexWrapper>
      </FlexWrapper>
    </>
  );
};
